export const SET_EVENT_FORM = 'SET_EVENT_FORM',
  SET_EVENT = 'SET_EVENT',
  REMOVE_EVENT = 'REMOVE_EVENT',
  EXPAND_EVENT = 'EXPAND_EVENT',
  SET_EDIT_EVENT = 'SET_EDIT_EVENT',
  SET_NEW_EVENT_DATA = 'SET_NEW_EVENT_DATA';